apiVersion: apps/v1
kind: Deployment
metadata:
  name: hswnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hswnginx
  template:
    metadata:
      labels:
        run: hswnginx
    spec:
      containers:
      - image: nginx
        name: hswnginx
        ports:
        - containerPort: 80
