apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-app
      strategy:
  blueGreen: 
    #activeService는 이전의 배포된 Blue 서비스
    activeService: rollout-bluegreen-active

    #previewService는 새롭게 배포될 Green 서비스
    previewService: rollout-bluegreen-preview

    #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
    autoPromotionEnabled: false
    
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: hamsw1005/python:test9
        imagePullPolicy: IfNotPresent
        name: python

      
      
      
#   template:
#     metadata:
#       labels:
#         run: flask-app
#     spec:
#       containers:
#       - image: hamsw1005/python:test7
#         name: flask-app
#         ports:
#         - containerPort: 5000
