apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"nhn-gitops"},"name":"mynginx","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"run":"mynginx"}},"template":{"metadata":{"labels":{"run":"mynginx"}},"spec":{"containers":[{"image":"nginx","name":"mynginx","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: '2022-11-18T05:34:39Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: nhn-gitops
  name: mynginx
  namespace: default
  resourceVersion: '171885'
  uid: 43e49626-f55c-40c1-b4d8-304a44d3b3cd
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: mynginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mynginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: mynginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: '2022-11-18T05:34:43Z'
      lastUpdateTime: '2022-11-18T05:34:43Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2022-11-18T05:34:39Z'
      lastUpdateTime: '2022-11-18T05:34:43Z'
      message: ReplicaSet "mynginx-584b47749f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mynginx
# spec:
#   replicas: 5
#   selector:
#     matchLabels:
#       run: mynginx
#   template:
#     metadata:
#       labels:
#         run: mynginx
#     spec:
#       containers:
#       - image: nginx
#         name: mynginx
#         ports:
#         - containerPort: 80
