apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: hamsw1005/python:test7
        imagePullPolicy: IfNotPresent
        name: python

      
      
      
#   template:
#     metadata:
#       labels:
#         run: flask-app
#     spec:
#       containers:
#       - image: hamsw1005/python:test7
#         name: flask-app
#         ports:
#         - containerPort: 5000
