apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingressclass.kubernetes.io/is-default-class: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: b90a9d57-nks-kr1.container.nhncloud.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mynginx
            port:
              number: 80
