apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"nhn-gitops"},"name":"mynginx","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"run":"mynginx"}}}
  creationTimestamp: '2022-11-18T05:34:39Z'
  labels:
    app.kubernetes.io/instance: nhn-gitops
  name: mynginx
  namespace: default
  resourceVersion: '171825'
  uid: 9eaa864b-e736-4a4c-817b-c2fec808a6a2
spec:
  clusterIP: 10.254.139.228
  clusterIPs:
    - 10.254.139.228
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: mynginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}




# apiVersion: v1
# kind: Service
# metadata:
#   name: mynginx
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     run: mynginx
