apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynginx-traefik-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: 103.218.159.38 #https://b90a9d57-nks-kr1.container.nhncloud.com:6443 #133.186.152.235
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hswnginx
            port:
              number: 80
